import React, { ReactElement, useContext } from "react";
import { ThemeContext } from "pages/_app";
import {
  DarkModeToggle,
  IconDiv,
  H1,
  H2,
  P,
  DateText,
  Logo,
  SearchInput,
} from "components";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import * as S from "./style";

const Home: NextPage = () => {
  const { colorTheme, toggleColorTheme } = useContext(ThemeContext);

  return (
    <S.Container colorTheme={colorTheme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkModeToggle />
      <Logo />
      <main>
        <h1>블로그 입니다</h1>
        <H1>안녕하세요</H1>
        <H2>안녕하세요2</H2>
        <DateText>2020년 1월 1일</DateText>
        <P>안녕하세요4</P>
        <IconDiv />
        <SearchInput />
      </main>
    </S.Container>
  );
};

export default Home;
