import React, { ReactElement, useContext } from "react";
import { ThemeContext } from "pages/_app";
import { HomeTemplate } from "components";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import * as S from "./style";

const Home: NextPage = () => {
  const { colorTheme, toggleColorTheme } = useContext(ThemeContext);

  return (
    <S.Container colorTheme={colorTheme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate />
    </S.Container>
  );
};

export default Home;
